// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bagzeqcdnavtvveglvrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZ3plcWNkbmF2dHZ2ZWdsdnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzI0ODcsImV4cCI6MjA2Njg0ODQ4N30.-IWOQ9jpZ8Cnmaf8FM8YtmKardzz-c0msPmZSadOApE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});